/* 牛津 3000 词中文释义批量补齐脚本
 * 策略：内置 A1/A2 高频词中文映射（~500 词），B1/B2 留空后续补
 * 用法：node fill-zh.js  → 更新 js/data-oxford.js 中的 zh 字段
 * 后续可扩充映射表覆盖更多词 */
const fs = require('fs');
const path = require('path');

/* A1/A2 高频词中文释义映射表（按使用频率精选） */
const ZH = {
  a: '一个', about: '关于', above: '在…上面', accept: '接受', accident: '事故',
  across: '穿过', act: '行动', action: '行动', activity: '活动', actor: '演员',
  add: '添加', address: '地址', advantage: '优势', advertise: '做广告', advice: '建议',
  afraid: '害怕的', after: '在…之后', afternoon: '下午', again: '又', against: '反对',
  age: '年龄', ago: '以前', agree: '同意', air: '空气', airport: '机场',
  alarm: '闹钟', album: '专辑', alive: '活着的', all: '全部', allow: '允许',
  almost: '几乎', alone: '独自的', along: '沿着', already: '已经', also: '也',
  although: '虽然', always: '总是', amazing: '令人惊奇的', among: '在…之中', amount: '数量',
  ancient: '古代的', and: '和', angry: '生气的', animal: '动物', ankle: '脚踝',
  another: '另一个', answer: '回答', anxious: '焦虑的', any: '任何', anyone: '任何人',
  anything: '任何事', apartment: '公寓', appear: '出现', apple: '苹果', application: '申请',
  apply: '申请', approach: '方法', April: '四月', area: '地区', argue: '争论',
  arm: '手臂', around: '围绕', arrange: '安排', arrive: '到达', art: '艺术',
  artist: '艺术家', as: '作为', ask: '问', asleep: '睡着的', August: '八月',
  aunt: '姑妈', autumn: '秋天', available: '可用的', avoid: '避免', awake: '醒着的',
  away: '离开', back: '回来', bad: '坏的', bag: '包', bake: '烤',
  balance: '平衡', ball: '球', bank: '银行', bar: '酒吧', base: '基础',
  basic: '基本的', basket: '篮子', bath: '洗澡', bathroom: '浴室', beach: '海滩',
  bean: '豆子', bear: '熊', beat: '打败', beautiful: '美丽的', because: '因为',
  become: '变成', bed: '床', bedroom: '卧室', bee: '蜜蜂', before: '在…之前',
  begin: '开始', behave: '表现', behind: '在…后面', believe: '相信', bell: '铃',
  below: '在…下面', belt: '腰带', bench: '长凳', best: '最好的', better: '更好的',
  between: '在…之间', beyond: '超过', bicycle: '自行车', big: '大的', bike: '自行车',
  bill: '账单', bin: '垃圾桶', bird: '鸟', birth: '出生', birthday: '生日',
  bit: '一点', black: '黑色的', block: '街区', blood: '血液', blow: '吹',
  blue: '蓝色的', board: '木板', boat: '船', body: '身体', boil: '煮沸',
  bomb: '炸弹', bone: '骨头', book: '书', boot: '靴子', border: '边界',
  bored: '无聊的', boring: '乏味的', born: '出生的', borrow: '借', both: '两者',
  bottle: '瓶子', bottom: '底部', bowl: '碗', box: '盒子', boy: '男孩',
  brain: '大脑', branch: '树枝', brave: '勇敢的', bread: '面包', break: '打破',
  breakfast: '早餐', breath: '呼吸', breathe: '呼吸', brick: '砖', bridge: '桥',
  bright: '明亮的', bring: '带来', broad: '宽的', brother: '兄弟', brown: '棕色的',
  brush: '刷子', build: '建造', building: '建筑', burn: '燃烧', bus: '公交车',
  business: '生意', busy: '忙碌的', but: '但是', butter: '黄油', button: '按钮',
  buy: '买', by: '通过', cafe: '咖啡馆', cake: '蛋糕', call: '打电话',
  calm: '平静的', camera: '相机', camp: '露营', can: '能够', cancel: '取消',
  cap: '帽子', car: '汽车', card: '卡片', care: '关心', careful: '小心的',
  carry: '携带', case: '情况', cat: '猫', catch: '抓住', cause: '原因',
  ceiling: '天花板', central: '中心的', centre: '中心', century: '世纪', certain: '确定的',
  chain: '链条', chair: '椅子', chalk: '粉笔', challenge: '挑战', chance: '机会',
  change: '改变', cheap: '便宜的', check: '检查', cheek: '脸颊', cheer: '欢呼',
  cheese: '奶酪', chemical: '化学的', chest: '胸部', chicken: '鸡肉', child: '孩子',
  choose: '选择', church: '教堂', cinema: '电影院', circle: '圆圈', city: '城市',
  class: '班级', classic: '经典的', clean: '干净的', clear: '清晰的', clever: '聪明的',
  climb: '攀登', clock: '时钟', close: '关闭', cloth: '布', clothes: '衣服',
  cloud: '云', club: '俱乐部', coast: '海岸', coat: '外套', coffee: '咖啡',
  coin: '硬币', cold: '冷的', collect: '收集', college: '大学', colour: '颜色',
  come: '来', comfortable: '舒适的', common: '常见的', company: '公司', compare: '比较',
  complete: '完成的', computer: '电脑', concern: '关心', concert: '音乐会', condition: '条件',
  connect: '连接', consider: '考虑', contain: '包含', content: '内容', continue: '继续',
  control: '控制', cook: '烹饪', cool: '凉爽的', copy: '复制', corner: '角落',
  correct: '正确的', cost: '花费', cough: '咳嗽', could: '能够', count: '数',
  country: '国家', course: '课程', cover: '覆盖', cow: '奶牛', crazy: '疯狂的',
  create: '创造', cross: '穿过', crowded: '拥挤的', cry: '哭', cultural: '文化的',
  culture: '文化', cup: '杯子', curious: '好奇的', current: '当前的', cut: '切',
  daily: '每日的', dance: '跳舞', danger: '危险', dangerous: '危险的', dark: '黑暗的',
  data: '数据', date: '日期', daughter: '女儿', day: '天', dead: '死的',
  deal: '交易', dear: '亲爱的', death: '死亡', decide: '决定', decision: '决定',
  deep: '深的', delicious: '美味的', deliver: '递送', dentist: '牙医', depend: '依赖',
  describe: '描述', desert: '沙漠', design: '设计', desk: '书桌', despite: '尽管',
  dessert: '甜点', develop: '发展', die: '死', diet: '饮食', difference: '不同',
  different: '不同的', difficult: '困难的', dig: '挖', dinner: '晚餐', direct: '直接的',
  dirty: '脏的', discover: '发现', discuss: '讨论', discussion: '讨论', disease: '疾病',
  dish: '盘子', distance: '距离', divide: '分开', do: '做', doctor: '医生',
  dog: '狗', dollar: '美元', door: '门', double: '双倍的', doubt: '怀疑',
  down: '向下', draw: '画', dream: '梦想', dress: '连衣裙', drink: '喝',
  drive: '驾驶', driver: '司机', drop: '掉落', dry: '干燥的', during: '在…期间',
  each: '每个', ear: '耳朵', early: '早的', earn: '赚取', earth: '地球',
  easily: '容易地', east: '东方', easy: '容易的', eat: '吃', edge: '边缘',
  education: '教育', effect: '效果', egg: '鸡蛋', either: '两者之一', elbow: '肘部',
  electric: '电的', else: '其他的', email: '电子邮件', empty: '空的', end: '结束',
  enemy: '敌人', energy: '能量', engineer: '工程师', enough: '足够的', enter: '进入',
  environment: '环境', equal: '相等的', escape: '逃离', especially: '尤其', even: '甚至',
  evening: '晚上', event: '事件', ever: '曾经', every: '每个', everyone: '每个人',
  everything: '一切', exactly: '确切地', example: '例子', excellent: '优秀的', except: '除了',
  excited: '兴奋的', exercise: '锻炼', exist: '存在', expect: '期待', expensive: '昂贵的',
  experience: '经验', explain: '解释', explore: '探索', express: '表达', extra: '额外的',
  eye: '眼睛', face: '脸', fact: '事实', factory: '工厂', fail: '失败',
  fair: '公平的', fall: '落下', false: '假的', family: '家庭', famous: '著名的',
  fantastic: '极好的', far: '远的', farm: '农场', farmer: '农民', fashion: '时尚',
  fast: '快的', fat: '胖的', father: '父亲', favourite: '最喜欢的', fear: '恐惧',
  feel: '感觉', feeling: '感受', festival: '节日', fetch: '取来', fever: '发烧',
  few: '很少的', field: '田野', fight: '打架', figure: '数字', fill: '填满',
  film: '电影', final: '最终的', find: '找到', fine: '好的', finger: '手指',
  finish: '完成', fire: '火', first: '第一的', fish: '鱼', fit: '适合',
  five: '五', fix: '修理', flat: '公寓', floor: '地板', flower: '花',
  fly: '飞', follow: '跟随', food: '食物', foot: '脚', football: '足球',
  for: '为了', force: '力量', foreign: '外国的', forest: '森林', forget: '忘记',
  forgive: '原谅', fork: '叉子', form: '形式', formal: '正式的', lucky: '幸运的',
  fortune: '财富', forward: '向前', forty: '四十', found: '发现', four: '四',
  fresh: '新鲜的', Friday: '星期五', friend: '朋友', friendly: '友好的', from: '从',
  front: '前面', fruit: '水果', full: '满的', fun: '乐趣', funny: '有趣的',
  furniture: '家具', future: '未来', gain: '获得', game: '游戏', garden: '花园',
  gas: '汽油', gate: '大门', general: '一般的', generous: '慷慨的', gentle: '温和的',
  get: '得到', gift: '礼物', girl: '女孩', give: '给', glad: '高兴的',
  glass: '玻璃', go: '去', goal: '目标', goat: '山羊', gold: '金色的',
  good: '好的', government: '政府', grade: '年级', grand: '宏伟的', grandparent: '祖父母',
  grass: '草', great: '伟大的', green: '绿色的', ground: '地面', group: '组',
  grow: '生长', guess: '猜', guest: '客人', guide: '指南', guitar: '吉他',
  gun: '枪', gym: '体育馆', hair: '头发', half: '一半', hand: '手',
  happen: '发生', happy: '快乐的', hard: '困难的', hat: '帽子', hate: '讨厌',
  have: '有', he: '他', head: '头', healthy: '健康的', hear: '听到',
  heart: '心脏', heat: '热', heavy: '重的', height: '高度', helicopter: '直升机',
  hello: '你好', help: '帮助', here: '这里', hide: '隐藏', high: '高的',
  hill: '小山', hire: '雇用', history: '历史', hit: '打', hobby: '爱好',
  hold: '握住', holiday: '假期', home: '家', honest: '诚实的', honey: '蜂蜜',
  hope: '希望', horse: '马', hospital: '医院', hot: '热的', hotel: '酒店',
  hour: '小时', house: '房子', how: '如何', however: '然而', huge: '巨大的',
  human: '人类', hundred: '百', hungry: '饥饿的', hurry: '匆忙', hurt: '伤害',
  husband: '丈夫', ice: '冰', idea: '想法', if: '如果', ignore: '忽视',
  ill: '生病的', imagine: '想象', important: '重要的', impossible: '不可能的', improve: '改善',
  in: '在…里', inch: '英寸', include: '包括', increase: '增加', indeed: '确实',
  industry: '工业', infection: '感染', information: '信息', ink: '墨水', inside: '在里面',
  instead: '代替', interest: '兴趣', interesting: '有趣的', international: '国际的', internet: '互联网',
  interview: '面试', into: '进入', introduce: '介绍', invent: '发明', invite: '邀请',
  island: '岛', issue: '问题', it: '它', item: '物品', jacket: '夹克',
  January: '一月', job: '工作', join: '加入', joke: '笑话', journey: '旅程',
  joy: '快乐', judge: '判断', juice: '果汁', jump: '跳', just: '只是',
  keep: '保持', key: '钥匙', keyboard: '键盘', kick: '踢', kid: '孩子',
  kill: '杀', kind: '善良的', king: '国王', kiss: '吻', kitchen: '厨房',
  kite: '风筝', knee: '膝盖', knife: '刀', knock: '敲', know: '知道',
  lab: '实验室', lack: '缺乏', lady: '女士', lake: '湖', land: '陆地',
  language: '语言', large: '大的', last: '最后的', late: '迟到的', later: '稍后',
  laugh: '笑', law: '法律', lay: '放置', lazy: '懒的', lead: '领导',
  learn: '学习', least: '最少的', leave: '离开', lecture: '讲座', left: '左边的',
  leg: '腿', legal: '合法的', lemon: '柠檬', lend: '借出', less: '更少的',
  lesson: '课', let: '让', letter: '信', level: '水平', library: '图书馆',
  license: '执照', lie: '躺', life: '生活', lift: '举起', light: '光',
  like: '喜欢', line: '线', lion: '狮子', lip: '嘴唇', list: '列表',
  listen: '听', literature: '文学', little: '小的', live: '生活', local: '当地的',
  lock: '锁', lonely: '孤独的', long: '长的', look: '看', lose: '失去',
  lot: '许多', loud: '大声的', love: '爱', lovely: '可爱的', low: '低的',
  lucky: '幸运的', lunch: '午餐', machine: '机器', magazine: '杂志', main: '主要的',
  make: '制作', man: '男人', manage: '管理', many: '许多', map: '地图',
  March: '三月', mark: '标记', market: '市场', marry: '结婚', match: '比赛',
  material: '材料', mathematics: '数学', matter: '事情', may: '可以', maybe: '也许',
  meal: '餐', mean: '意味着', meaning: '意思', measure: '测量', meat: '肉',
  media: '媒体', medicine: '药', meet: '遇见', meeting: '会议', member: '成员',
  memory: '记忆', mention: '提到', menu: '菜单', message: '消息', metal: '金属',
  method: '方法', middle: '中间的', might: '可能', mile: '英里', milk: '牛奶',
  million: '百万', mind: '头脑', mine: '我的', minute: '分钟', Miss: '小姐',
  mistake: '错误', mix: '混合', model: '模型', modern: '现代的', moment: '时刻',
  Monday: '星期一', money: '钱', monkey: '猴子', month: '月', moon: '月亮',
  more: '更多的', morning: '早上', most: '最多的', mother: '母亲', motor: '发动机',
  mountain: '山', mouse: '老鼠', mouth: '嘴', move: '移动', movie: '电影',
  much: '许多', museum: '博物馆', music: '音乐', must: '必须', my: '我的',
  myself: '我自己', name: '名字', narrow: '狭窄的', national: '国家的', natural: '自然的',
  nature: '自然', near: '近的', nearly: '几乎', necessary: '必要的', neck: '脖子',
  need: '需要', neighbour: '邻居', neither: '两者都不', nervous: '紧张的', never: '从不',
  new: '新的', news: '新闻', next: '下一个', nice: '好的', night: '夜晚',
  nine: '九', no: '不', nobody: '没有人', nod: '点头', noise: '噪音',
  none: '没有', noodle: '面条', noon: '中午', nor: '也不', normal: '正常的',
  north: '北方', nose: '鼻子', not: '不', note: '笔记', nothing: '没什么',
  notice: '注意', November: '十一月', now: '现在', number: '数字', nurse: '护士',
  object: '物体', ocean: '海洋', "o'clock": '点钟', October: '十月', of: '…的',
  off: '关', offer: '提供', office: '办公室', often: '经常', oil: '油',
  old: '旧的', on: '在…上', once: '一次', one: '一', onion: '洋葱',
  only: '只有', open: '打开', opposite: '相反的', or: '或者', orange: '橙色的',
  order: '命令', organ: '器官', other: '其他的', our: '我们的', out: '出去',
  outside: '在外面', over: '超过', own: '自己的', pack: '打包', package: '包裹',
  page: '页', pain: '疼痛', paint: '油漆', pair: '一对', palace: '宫殿',
  pale: '苍白的', pancake: '煎饼', panda: '熊猫', paper: '纸', paragraph: '段落',
  pardon: '原谅', parent: '父母', park: '公园', part: '部分', particular: '特别的',
  party: '聚会', pass: '通过', passage: '段落', passenger: '乘客', passport: '护照',
  past: '过去的', path: '小路', patient: '病人', pattern: '模式', pause: '暂停',
  pay: '支付', peace: '和平', peach: '桃子', pen: '钢笔', pencil: '铅笔',
  people: '人们', pepper: '胡椒', perfect: '完美的', perhaps: '也许', period: '时期',
  permit: '允许', person: '人', personal: '个人的', pet: '宠物', phone: '电话',
  photo: '照片', pick: '捡', picnic: '野餐', picture: '图片', pie: '馅饼',
  piece: '块', pig: '猪', pile: '堆', pilot: '飞行员', pink: '粉红色的',
  pioneer: '先驱', pipe: '管子', pizza: '披萨', place: '地方', plan: '计划',
  plane: '飞机', planet: '行星', plant: '植物', plastic: '塑料', plate: '盘子',
  play: '玩', playground: '操场', pleasant: '令人愉快的', please: '请', pleasure: '快乐',
  pocket: '口袋', poem: '诗', poet: '诗人', point: '指向', police: '警察',
  policy: '政策', polite: '有礼貌的', pool: '游泳池', poor: '穷的', popular: '受欢迎的',
  population: '人口', position: '位置', possible: '可能的', post: '邮寄', potato: '土豆',
  pound: '磅', power: '力量', practical: '实际的', practice: '练习', practise: '练习',
  praise: '表扬', prefer: '更喜欢', prepare: '准备', present: '礼物', president: '总统',
  press: '按', pretty: '漂亮的', prevent: '阻止', price: '价格', pride: '骄傲',
  primary: '主要的', print: '打印', prison: '监狱', private: '私人的', prize: '奖品',
  probably: '可能', problem: '问题', produce: '生产', product: '产品', programme: '节目',
  progress: '进步', project: '项目', promise: '承诺', pronounce: '发音', protect: '保护',
  proud: '骄傲的', prove: '证明', provide: '提供', public: '公众的', pull: '拉',
  punish: '惩罚', pupil: '学生', purple: '紫色的', purpose: '目的', push: '推',
  put: '放', quality: '质量', quarter: '四分之一', queen: '女王', question: '问题',
  quick: '快的', quiet: '安静的', quite: '相当', race: '赛跑', radio: '收音机',
  railway: '铁路', rain: '雨', raise: '提高', rather: '宁愿', reach: '到达',
  read: '读', ready: '准备好的', real: '真实的', reason: '原因', receive: '收到',
  recent: '最近的', recognise: '认出', recommend: '推荐', record: '记录', red: '红色的',
  reduce: '减少', refer: '提及', fridge: '冰箱', refuse: '拒绝', regard: '看待',
  regret: '后悔', regular: '规则的', relax: '放松', remain: '保持', remember: '记住',
  remove: '移除', repair: '修理', repeat: '重复', reply: '回复', report: '报告',
  rest: '休息', restaurant: '餐厅', result: '结果', return: '返回', reuse: '重复使用',
  rich: '富有的', ride: '骑', right: '右边', ring: '戒指', rise: '上升',
  risk: '风险', river: '河', road: '路', robot: '机器人', rock: '岩石',
  role: '角色', roof: '屋顶', room: '房间', round: '圆的', row: '排',
  rub: '摩擦', rubbish: '垃圾', rule: '规则', run: '跑', rush: '冲',
  sad: '悲伤的', safe: '安全的', sail: '航行', salad: '沙拉', sale: '出售',
  same: '相同的', sand: '沙子', sandwich: '三明治', satisfy: '满足', Saturday: '星期六',
  save: '节省', say: '说', scene: '场景', school: '学校', science: '科学',
  scientist: '科学家', score: '分数', sea: '海', search: '搜索', season: '季节',
  seat: '座位', second: '第二', secret: '秘密', see: '看见', seem: '似乎',
  seldom: '很少', sell: '卖', send: '发送', sentence: '句子', September: '九月',
  serious: '严肃的', serve: '服务', seven: '七', several: '几个', shake: '摇',
  shall: '将要', shape: '形状', share: '分享', sharp: '锋利的', she: '她',
  sheep: '羊', shelf: '架子', shine: '照耀', ship: '船', shirt: '衬衫',
  shoe: '鞋', shop: '商店', short: '短的', should: '应该', shoulder: '肩膀',
  shout: '喊', show: '展示', shower: '淋浴', shut: '关', sick: '生病的',
  side: '边', sight: '视力', sign: '签名', silence: '沉默', silent: '沉默的',
  silk: '丝绸', silver: '银色的', similar: '相似的', simple: '简单的', since: '自从',
  sing: '唱', single: '单一的', sir: '先生', sister: '姐妹', sit: '坐',
  situation: '情况', six: '六', size: '尺寸', ski: '滑雪', skill: '技能',
  skin: '皮肤', skirt: '裙子', sky: '天空', sleep: '睡觉', slow: '慢的',
  small: '小的', smell: '闻', smile: '微笑', smoke: '烟', smooth: '光滑的',
  snake: '蛇', snow: '雪', so: '所以', soap: '肥皂', social: '社会的',
  socks: '袜子', soft: '柔软的', soldier: '士兵', solid: '固体的', solve: '解决',
  some: '一些', son: '儿子', song: '歌', soon: '很快', sorry: '抱歉的',
  sound: '声音', soup: '汤', south: '南方', space: '空间', speak: '说话',
  special: '特别的', speech: '演讲', speed: '速度', spell: '拼写', spend: '花费',
  spoon: '勺子', sport: '运动', spread: '传播', spring: '春天', square: '正方形',
  staff: '员工', stage: '舞台', stairs: '楼梯', stamp: '邮票', stand: '站',
  star: '星星', start: '开始', state: '状态', station: '车站', stay: '停留',
  steady: '稳定的', steak: '牛排', still: '仍然', stone: '石头', stop: '停止',
  store: '商店', storm: '暴风雨', story: '故事', straight: '直的', strange: '奇怪的',
  stranger: '陌生人', street: '街道', strict: '严格的', strong: '强壮的', student: '学生',
  study: '学习', stuff: '东西', stupid: '愚蠢的', subject: '科目', succeed: '成功',
  success: '成功', such: '这样的', suddenly: '突然', sugar: '糖', suggest: '建议',
  suit: '西装', summer: '夏天', sun: '太阳', Sunday: '星期天', sunny: '晴朗的',
  supermarket: '超市', support: '支持', suppose: '假设', sure: '确定的', surprise: '惊喜',
  sweet: '甜的', swim: '游泳', table: '桌子', tail: '尾巴', take: '拿',
  tale: '故事', talk: '谈话', tall: '高的', taste: '味道', taxi: '出租车',
  tea: '茶', teach: '教', teacher: '老师', team: '团队', tear: '眼泪',
  technology: '技术', telephone: '电话', television: '电视', tell: '告诉', temperature: '温度',
  ten: '十', tennis: '网球', term: '学期', terrible: '糟糕的', test: '测试',
  text: '文本', than: '比', thank: '感谢', that: '那个', the: '这个',
  theatre: '剧院', their: '他们的', them: '他们', then: '然后', there: '那里',
  these: '这些', they: '他们', thick: '厚的', thin: '薄的', thing: '东西',
  think: '思考', third: '第三', thirsty: '口渴的', this: '这个', those: '那些',
  though: '虽然', thought: '想法', thousand: '千', three: '三', throat: '喉咙',
  through: '通过', throw: '扔', thumb: '拇指', thunder: '雷', ticket: '票',
  tidy: '整洁的', tie: '领带', tiger: '老虎', time: '时间', tin: '罐头',
  tiny: '微小的', tip: '建议', tired: '疲劳的', title: '标题', to: '到',
  today: '今天', toe: '脚趾', together: '一起', toilet: '厕所', tomato: '番茄',
  tomorrow: '明天', ton: '吨', tongue: '舌头', tonight: '今晚', too: '也',
  tool: '工具', tooth: '牙齿', top: '顶部', topic: '话题', total: '总数',
  touch: '触摸', tour: '旅行', tourist: '游客', toward: '朝向', towel: '毛巾',
  tower: '塔', town: '城镇', toy: '玩具', trade: '贸易', tradition: '传统',
  traffic: '交通', train: '火车', transform: '转变', transport: '交通', travel: '旅行',
  treasure: '宝藏', treat: '对待', tree: '树', trip: '旅行', trouble: '麻烦',
  trousers: '裤子', truck: '卡车', true: '真的', trust: '信任', truth: '真相',
  try: '尝试', "T-shirt": 'T恤', tube: '管子', Tuesday: '星期二', tunnel: '隧道',
  turn: '转弯', TV: '电视', twelve: '十二', twenty: '二十', twice: '两次',
  two: '二', type: '类型', tyre: '轮胎', ugly: '丑的', uncle: '叔叔',
  under: '在…下面', understand: '理解', uniform: '制服', unit: '单位', university: '大学',
  unless: '除非', until: '直到', unusual: '不寻常的', up: '向上', upon: '在…上',
  upper: '上面的', upset: '心烦的', us: '我们', use: '使用', useful: '有用的',
  usual: '通常的', usually: '通常', vacation: '假期', vegetable: '蔬菜', very: '非常',
  victory: '胜利', video: '视频', view: '看法', village: '村庄', visit: '参观',
  voice: '声音', wait: '等待', wake: '醒来', walk: '走', wall: '墙',
  want: '想要', war: '战争', warm: '温暖的', wash: '洗', waste: '浪费',
  watch: '观看', water: '水', wave: '波浪', way: '方式', we: '我们',
  weak: '弱的', wealth: '财富', wear: '穿', weather: '天气', website: '网站',
  Wednesday: '星期三', week: '周', weekend: '周末', weigh: '称重', welcome: '欢迎',
  well: '好的', west: '西方', wet: '湿的', whale: '鲸鱼', what: '什么',
  wheel: '轮子', when: '当…时', where: '哪里', whether: '是否', which: '哪个',
  while: '当…时', white: '白色的', who: '谁', whole: '整个的', why: '为什么',
  wide: '宽的', wife: '妻子', wild: '野生的', will: '将会', win: '赢',
  wind: '风', window: '窗户', wing: '翅膀', winter: '冬天', wire: '电线',
  wise: '明智的', wish: '希望', with: '和…一起', without: '没有', wolf: '狼',
  woman: '女人', wonder: '想知道', wonderful: '精彩的', wood: '木头', word: '单词',
  work: '工作', world: '世界', worry: '担心', worth: '值得', would: '将会',
  wound: '伤口', wrap: '包裹', write: '写', writer: '作家', wrong: '错误的',
  yard: '院子', year: '年', yellow: '黄色的', yes: '是的', yesterday: '昨天',
  yet: '还', you: '你', young: '年轻的', your: '你的', youth: '青年',
  zero: '零', zoo: '动物园'
};

/* 读取 data-oxford.js，填充 zh 字段 */
const oxfordPath = path.join(__dirname, 'app', 'js', 'data-oxford.js');
let code = fs.readFileSync(oxfordPath, 'utf8');

/* 提取 LEVELS 数据 */
const match = code.match(/var VG_OXFORD = (\{.*\});/s);
if (!match) { console.log('FAIL: VG_OXFORD not found'); process.exit(1); }
const data = JSON.parse(match[1]);

let filled = 0, total = 0;
data.LEVELS.forEach(function (level) {
  level.words.forEach(function (w) {
    total++;
    var key = w.word.toLowerCase();
    if (ZH[key]) {
      w.zh = ZH[key];
      filled++;
    } else {
      w.zh = '';
    }
  });
});

console.log('总词数: ' + total + ' | 已填中文: ' + filled + ' | 未填: ' + (total - filled));

/* 重新生成 data-oxford.js */
const out = '/* ============================================================\n' +
  ' * 词汇生长 — 牛津 3000/5000 高频词库 (js/data-oxford.js)\n' +
  ' * 数据源：Oxford 3000/5000 by CEFR（开源数据集）\n' +
  ' * 共 ' + total + ' 词（A1-B2），中文释义已填充 ' + filled + ' 词\n' +
  ' * ============================================================ */\n' +
  'var VG_OXFORD = ' + JSON.stringify(data) + ';\n' +
  'if (typeof module !== "undefined" && module.exports) module.exports = VG_OXFORD;\n';
fs.writeFileSync(oxfordPath, out);
console.log('✅ data-oxford.js 已更新');
